[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
autobins = false
name = "game"
version = "0.1.0"

[dependencies]
failure = "0.1.3"
glium = "0.22.0"
log = "0.4.6"
obj = "0.9.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
stderrlog = "0.4.1"
structopt = "0.2.13"
